//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Integrated_B2B.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DB_Customer
    {
        public DB_Customer()
        {
            this.DB_Sales_Bill = new HashSet<DB_Sales_Bill>();
        }
    
        public int Customer_Id { get; set; }
        public string Customer_Name { get; set; }
        public Nullable<int> Customer_Type { get; set; }
        public Nullable<int> Channel_Type { get; set; }
        public Nullable<int> Loyalty_Program { get; set; }
        public string Billing_Address { get; set; }
        public string Route { get; set; }
        public string Salesman { get; set; }
        public Nullable<bool> Active { get; set; }
    
        public virtual DB_Channel_Type DB_Channel_Type { get; set; }
        public virtual DB_Customer_Type DB_Customer_Type { get; set; }
        public virtual DB_Loyalty_Program DB_Loyalty_Program { get; set; }
        public virtual ICollection<DB_Sales_Bill> DB_Sales_Bill { get; set; }
    }
}
