//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Integrated_B2B.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DB_Invoice
    {
        public int id { get; set; }
        public string Invoice_Id { get; set; }
        public int cid { get; set; }
        public Nullable<System.DateTime> DateOfPurchase { get; set; }
        public Nullable<double> Vat { get; set; }
        public Nullable<double> Duty { get; set; }
        public Nullable<double> Grand_Total { get; set; }
    
        public virtual DB_Company DB_Company { get; set; }
    }
}
