//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Integrated_B2B.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DB_Invoice_Product
    {
        public int id { get; set; }
        public Nullable<int> Prod_Id { get; set; }
        public string Invoice_Id { get; set; }
        public Nullable<double> Quantity { get; set; }
        public string Unit { get; set; }
        public Nullable<System.DateTime> Mfg_Date { get; set; }
        public Nullable<double> Rate { get; set; }
        public Nullable<double> Amount { get; set; }
        public Nullable<System.DateTime> Exp_Date { get; set; }
    
        public virtual DB_Product DB_Product { get; set; }
    }
}
