//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Integrated_B2B.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DB_Loyalty_Program
    {
        public DB_Loyalty_Program()
        {
            this.DB_Customer = new HashSet<DB_Customer>();
        }
    
        public int Loyalty_Program_Id { get; set; }
        public string Loyalty_Program_Name { get; set; }
        public Nullable<double> Profit_On_CP { get; set; }
    
        public virtual ICollection<DB_Customer> DB_Customer { get; set; }
    }
}
