//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Integrated_B2B.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DB_Sales_Bill_Product
    {
        public int Id { get; set; }
        public string Bill_No { get; set; }
        public Nullable<int> Prod_Id { get; set; }
        public Nullable<double> Qty { get; set; }
        public Nullable<double> Amount { get; set; }
        public Nullable<double> Scheme { get; set; }
        public Nullable<double> Discount { get; set; }
        public Nullable<double> Rate { get; set; }
    
        public virtual DB_Product DB_Product { get; set; }
        public virtual DB_Sales_Bill DB_Sales_Bill { get; set; }
    }
}
