//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Integrated_B2B.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DB_Sales_Bill
    {
        public DB_Sales_Bill()
        {
            this.DB_Sales_Bill_Product = new HashSet<DB_Sales_Bill_Product>();
        }
    
        public string Bill_No { get; set; }
        public Nullable<System.DateTime> DateTime { get; set; }
        public Nullable<int> Customer_Id { get; set; }
        public Nullable<double> Total_Amount { get; set; }
        public Nullable<double> Deposit { get; set; }
        public Nullable<double> Dues { get; set; }
        public string Advance { get; set; }
        public Nullable<int> cid { get; set; }
    
        public virtual DB_Customer DB_Customer { get; set; }
        public virtual ICollection<DB_Sales_Bill_Product> DB_Sales_Bill_Product { get; set; }
    }
}
